# Config File Generated: 2017-03-16.12:00:20
- Kcu105Cryo:
    - FmcCtrl: !<value> 0x0
    - JesdRx:
        - ThresholdLow: !<value>
            - 0x5000
            - 0x5000
            - 0x5000
            - 0x5000
            - 0x0000
            - 0x0000
        - ThresholdHigh: !<value>
            - 0xa000
            - 0xa000
            - 0xa000
            - 0xa000
            - 0x0000
            - 0x0000
        - LinkErrMask: !<value> 0x3f
        - ScrambleEnable: !<value> Disabled
        - InvertSync: !<value> Regular
        - ResetGTs: !<value> 0x0
        - ClearErrors: !<value> 0x0
        - SubClass: !<value> 0x1
        - ReplaceEnable: !<value> Enabled
        - Enable: !<value> 0x0f
        - SysrefDelay: !<value> 0x00
    - AxiVersion:
        - MasterReset: !<value> 0x0
        - FpgaReloadAddress: !<value> 0x00000000
        - FpgaReload: !<value> 0x0
        - FpgaReloadHalt: !<value> 0x0
        - ScratchPad: !<value> 0x00000000
    - RssiServer:
        - MaxOutOfSeq: !<value> 0x00
        - MaxCumAck: !<value> 0x03
        - MaxNumRetrans: !<value> 0x02
        - NullSegTimeout: !<value> 0x00c8
        - CumAckTimeout: !<value> 0x0019
        - RetransTimeout: !<value> 0x0032
        - MaxSegSize: !<value> 0x0400
        - MaxOutsSeg: !<value> 0x08
        - Version: !<value> 0x1
        - InitSeqN: !<value> 0x80
        - HeaderChksumEn: !<value> 0x1
        - Mode: !<value> 0x0
        - InjectFault: !<value> 0x0
        - CloseConn: !<value> 0x0
        - OpenConn: !<value> 0x0
    - AxiSysMonUltraScale:
        - AlarmThresholdReg_25_16: !<value>
            - 0x00009a74
            - 0x00004da6
            - 0x00009a74
            - 0x00004d39
            - 0x00000000
            - 0x00000000
            - 0x00000000
            - 0x00000000
        - AlarmThresholdReg16: !<value> 0x00009a74
        - AlarmThresholdReg12: !<value> 0x00004963
        - AlarmThresholdReg_8_0: !<value>
            - 0x0000b723
            - 0x00004e81
            - 0x0000a147
            - 0x0000cb93
            - 0x0000aa5f
            - 0x00004963
            - 0x00009555
            - 0x0000af7b
            - 0x00004e81
        - SequenceReg_7_0: !<value>
            - 0x00004f01
            - 0x00000000
            - 0x00004f00
            - 0x00000000
            - 0x00000000
            - 0x00000000
            - 0x00000000
            - 0x00000000
        - SequenceReg9: !<value> 0x00000000
        - SequenceRegister8: !<value> 0x00000000
        - ConfigurationRegister: !<value>
            - 0x00000000
            - 0x000021df
            - 0x00009b00
            - 0x0000000f
        - IPIER: !<value> 0x00000000
        - GIER: !<value> 0x00000000
        - SYSMONRR: !<value> 0x00000000
        - CONVSTR: !<value> 0x00000000