cryo:
  AppTop:
    AppCore:
      AmcCryoCore:
        LMK:
          EnableSync: 0xFF
          EnableSysRef: 0x3
          LmkReg_0x0002: 0x00
          SyncBit: 0x1
          LmkReg_0x0100: 0x08
          LmkReg_0x0101: 0x55
          LmkReg_0x0103: 0x00
          LmkReg_0x0104: 0x22
          LmkReg_0x0105: 0x00
          LmkReg_0x0106: 0x70
          LmkReg_0x0107: 0x06
          LmkReg_0x0108: 0x61
          LmkReg_0x0109: 0x55
          LmkReg_0x010B: 0x01
          LmkReg_0x010C: 0x22
          LmkReg_0x010D: 0x00
          LmkReg_0x010E: 0x70
          LmkReg_0x010F: 0x9E
          LmkReg_0x0110: 0x61
          LmkReg_0x0111: 0x55
          LmkReg_0x0113: 0x01
          LmkReg_0x0114: 0x22
          LmkReg_0x0115: 0x00
          LmkReg_0x0116: 0x70
          LmkReg_0x0117: 0x9E
          LmkReg_0x0118: 0x61
          LmkReg_0x0119: 0x55
          LmkReg_0x011B: 0x02
          LmkReg_0x011C: 0x22
          LmkReg_0x011D: 0x00
          LmkReg_0x011E: 0x70
          LmkReg_0x011F: 0x00
          LmkReg_0x0120: 0x61
          LmkReg_0x0121: 0x55
          LmkReg_0x0123: 0x01
          LmkReg_0x0124: 0x22
          LmkReg_0x0125: 0x00
          LmkReg_0x0126: 0x70
          LmkReg_0x0127: 0x9E
          LmkReg_0x0128: 0x61
          LmkReg_0x0129: 0x55
          LmkReg_0x012B: 0x01
          LmkReg_0x012C: 0x22
          LmkReg_0x012D: 0x00
          LmkReg_0x012E: 0x70
          LmkReg_0x012F: 0x9E
          LmkReg_0x0130: 0x08
          LmkReg_0x0131: 0x55
          LmkReg_0x0133: 0x00
          LmkReg_0x0134: 0x22
          LmkReg_0x0135: 0x00
          LmkReg_0x0136: 0x70
          LmkReg_0x0137: 0x16
          LmkReg_0x0138: 0x00
          LmkReg_0x0139: 0x03
          LmkReg_0x013A: 0x04
          LmkReg_0x013B: 0x00
          LmkReg_0x013C: 0x00
          LmkReg_0x013D: 0x08
          LmkReg_0x013E: 0x03
          LmkReg_0x013F: 0x00
          LmkReg_0x0140: 0x00
          LmkReg_0x0141: 0x00
          LmkReg_0x0142: 0x00
          LmkReg_0x0143: 0x11
          LmkReg_0x0144: 0xFF
          LmkReg_0x0145: 0x7F
          LmkReg_0x0146: 0x10
          LmkReg_0x0147: 0x1A
          LmkReg_0x0148: 0x02
          LmkReg_0x0149: 0x42
          LmkReg_0x014A: 0x33
          LmkReg_0x014B: 0x16
          LmkReg_0x014C: 0x00
          LmkReg_0x014D: 0x00
          LmkReg_0x014E: 0x00
          LmkReg_0x014F: 0x7F
          LmkReg_0x0150: 0x01
          LmkReg_0x0151: 0x02
          LmkReg_0x0152: 0x00
          LmkReg_0x0153: 0x00
          LmkReg_0x0154: 0x78
          LmkReg_0x0155: 0x00
          LmkReg_0x0156: 0x7D
          LmkReg_0x0157: 0x00
          LmkReg_0x0158: 0x96
          LmkReg_0x0159: 0x06
          LmkReg_0x015A: 0x00
          LmkReg_0x015B: 0xD4
          LmkReg_0x015C: 0x20
          LmkReg_0x015D: 0x00
          LmkReg_0x015E: 0x00
          LmkReg_0x015F: 0x0B
          LmkReg_0x0160: 0x00
          LmkReg_0x0161: 0x01
          LmkReg_0x0162: 0x84
          LmkReg_0x0163: 0x00
          LmkReg_0x0164: 0x00
          LmkReg_0x0165: 0x05
          LmkReg_0x0171: 0xAA
          LmkReg_0x0172: 0x02
          LmkReg_0x0173: 0x0 
          LmkReg_0x0174: 0x0 
          LmkReg_0x017C: 0x15
          LmkReg_0x017D: 0x33
          LmkReg_0x0166: 0x00
          LmkReg_0x0167: 0x00
          LmkReg_0x0168: 0x05
          LmkReg_0x0169: 0x59
          LmkReg_0x016A: 0x20
          LmkReg_0x016B: 0x00
          LmkReg_0x016C: 0x00
          LmkReg_0x016D: 0x00
          LmkReg_0x016E: 0x13
        DAC[0]:
          DacReg[0]: 0x0018
          DacReg[1]: 0x0003
          DacReg[2]: 0x2000
          DacReg[3]: 0xa301
          DacReg[4]: 0xfcfc
          DacReg[5]: 0x000d
          DacReg[6]: 0xfcfc
          DacReg[7]: 0x3800
          DacReg[8]: 0x0000
          DacReg[9]: 0x0000
          DacReg[10]: 0x0000
          DacReg[11]: 0x0000
          DacReg[12]: 0x0400
          DacReg[13]: 0x0400
          DacReg[14]: 0x0400
          DacReg[15]: 0x0400
          DacReg[16]: 0x0000
          DacReg[17]: 0x0000
          DacReg[18]: 0x0000
          DacReg[19]: 0x0000
          DacReg[20]: 0x0000
          DacReg[21]: 0x0000
          DacReg[22]: 0x0000
          DacReg[23]: 0x0000
          DacReg[24]: 0x0000
          DacReg[25]: 0x0000
          DacReg[26]: 0x0020
          DacReg[27]: 0x0000
          DacReg[28]: 0x0000
          DacReg[29]: 0x0000
          DacReg[30]: 0x9999
          DacReg[31]: 0x9980
          DacReg[32]: 0x8008
          DacReg[33]: 0x0000
          DacReg[34]: 0x1b14
          DacReg[35]: 0xffff
          DacReg[36]: 0x0010
          DacReg[37]: 0x0000
          DacReg[38]: 0x0000
          DacReg[39]: 0x0000
          DacReg[40]: 0x0013
          DacReg[41]: 0xffff
          DacReg[42]: 0x0000
          DacReg[43]: 0x0000
          DacReg[44]: 0x0000
          DacReg[45]: 0x0000
          DacReg[46]: 0xffff
          DacReg[47]: 0x0004
          DacReg[48]: 0x0000
          DacReg[49]: 0x1000
          DacReg[50]: 0x0000
          DacReg[51]: 0x0000
          DacReg[52]: 0x0000
          DacReg[53]: 0x0000
          DacReg[54]: 0x0000
          DacReg[55]: 0x0000
          DacReg[56]: 0x0000
          DacReg[57]: 0x0000
          DacReg[58]: 0x0000
          DacReg[59]: 0x0000
          DacReg[60]: 0x0228
          DacReg[61]: 0x00a8
          DacReg[62]: 0x8908
          DacReg[63]: 0x0001
          DacReg[64]: 0x0000
          DacReg[65]: 0x0000
          DacReg[66]: 0x0000
          DacReg[67]: 0x0000
          DacReg[68]: 0x0000
          DacReg[69]: 0x0000
          DacReg[70]: 0x0044
          DacReg[71]: 0x190a
          DacReg[72]: 0x31c3
          DacReg[73]: 0x0004
          DacReg[74]: 0x0321
          DacReg[75]: 0x0501
          DacReg[76]: 0x1f01
          DacReg[77]: 0x0100
          DacReg[78]: 0x0f0f
          DacReg[79]: 0x1c61
          DacReg[80]: 0x0000
          DacReg[81]: 0x0017
          DacReg[82]: 0x00ff
          DacReg[83]: 0x0000
          DacReg[84]: 0x0017
          DacReg[85]: 0x00ff
          DacReg[86]: 0x0000
          DacReg[87]: 0x00ff
          DacReg[88]: 0x00ff
          DacReg[89]: 0x0000
          DacReg[90]: 0x00ff
          DacReg[91]: 0x00ff
          DacReg[92]: 0x2222
          DacReg[93]: 0x0000
          DacReg[94]: 0x0000
          DacReg[95]: 0x0123
          DacReg[96]: 0x4567
          DacReg[97]: 0x0211
          DacReg[98]: 0x0000
          DacReg[99]: 0x0000
          DacReg[100]: 0x1003
          DacReg[101]: 0x1003
          DacReg[102]: 0x3701
          DacReg[103]: 0xf30e
          DacReg[104]: 0xf90b
          DacReg[105]: 0x4a0b
          DacReg[106]: 0x170f
          DacReg[107]: 0xee0c
          DacReg[108]: 0x0007
          DacReg[109]: 0x00ff
          DacReg[110]: 0x0000
          DacReg[111]: 0x0000
          DacReg[112]: 0x0000
          DacReg[113]: 0x0000
          DacReg[114]: 0x0000
          DacReg[115]: 0x0000
          DacReg[116]: 0x0000
          DacReg[117]: 0x0000
          DacReg[118]: 0x0000
          DacReg[119]: 0x0000
          DacReg[120]: 0x0000
          DacReg[121]: 0x0000
          DacReg[122]: 0x0000
          DacReg[123]: 0x0000
          DacReg[124]: 0x0000
          DacReg[125]: 0x0000
          EnableTx: 0x1
        DAC[1]:
          DacReg[0]: 0x0018
          DacReg[1]: 0x0003
          DacReg[2]: 0x2000
          DacReg[3]: 0xa301
          DacReg[4]: 0xfcfc
          DacReg[5]: 0x000d
          DacReg[6]: 0xfcfc
          DacReg[7]: 0x3800
          DacReg[8]: 0x0000
          DacReg[9]: 0x0000
          DacReg[10]: 0x0000
          DacReg[11]: 0x0000
          DacReg[12]: 0x0400
          DacReg[13]: 0x0400
          DacReg[14]: 0x0400
          DacReg[15]: 0x0400
          DacReg[16]: 0x0000
          DacReg[17]: 0x0000
          DacReg[18]: 0x0000
          DacReg[19]: 0x0000
          DacReg[20]: 0x0000
          DacReg[21]: 0x0000
          DacReg[22]: 0x0000
          DacReg[23]: 0x0000
          DacReg[24]: 0x0000
          DacReg[25]: 0x0000
          DacReg[26]: 0x0020
          DacReg[27]: 0x0000
          DacReg[28]: 0x0000
          DacReg[29]: 0x0000
          DacReg[30]: 0x9999
          DacReg[31]: 0x9980
          DacReg[32]: 0x8008
          DacReg[33]: 0x0000
          DacReg[34]: 0x1b14
          DacReg[35]: 0xffff
          DacReg[36]: 0x0010
          DacReg[37]: 0x0000
          DacReg[38]: 0x0000
          DacReg[39]: 0x0000
          DacReg[40]: 0x0013
          DacReg[41]: 0xffff
          DacReg[42]: 0x0000
          DacReg[43]: 0x0000
          DacReg[44]: 0x0000
          DacReg[45]: 0x0000
          DacReg[46]: 0xffff
          DacReg[47]: 0x0004
          DacReg[48]: 0x0000
          DacReg[49]: 0x1000
          DacReg[50]: 0x0000
          DacReg[51]: 0x0000
          DacReg[52]: 0x0000
          DacReg[53]: 0x0000
          DacReg[54]: 0x0000
          DacReg[55]: 0x0000
          DacReg[56]: 0x0000
          DacReg[57]: 0x0000
          DacReg[58]: 0x0000
          DacReg[59]: 0x0000
          DacReg[60]: 0x0228
          DacReg[61]: 0x00a8
          DacReg[62]: 0x8908
          DacReg[63]: 0x0001
          DacReg[64]: 0x0000
          DacReg[65]: 0x0000
          DacReg[66]: 0x0000
          DacReg[67]: 0x0000
          DacReg[68]: 0x0000
          DacReg[69]: 0x0000
          DacReg[70]: 0x0044
          DacReg[71]: 0x190a
          DacReg[72]: 0x31c3
          DacReg[73]: 0x0004
          DacReg[74]: 0x0321
          DacReg[75]: 0x0501
          DacReg[76]: 0x1f01
          DacReg[77]: 0x0100
          DacReg[78]: 0x0f0f
          DacReg[79]: 0x1c61
          DacReg[80]: 0x0000
          DacReg[81]: 0x0017
          DacReg[82]: 0x00ff
          DacReg[83]: 0x0000
          DacReg[84]: 0x0017
          DacReg[85]: 0x00ff
          DacReg[86]: 0x0000
          DacReg[87]: 0x00ff
          DacReg[88]: 0x00ff
          DacReg[89]: 0x0000
          DacReg[90]: 0x00ff
          DacReg[91]: 0x00ff
          DacReg[92]: 0x2222
          DacReg[93]: 0x0000
          DacReg[94]: 0x0000
          DacReg[95]: 0x0123
          DacReg[96]: 0x4567
          DacReg[97]: 0x0211
          DacReg[98]: 0x0000
          DacReg[99]: 0x0000
          DacReg[100]: 0x1003
          DacReg[101]: 0x1003
          DacReg[102]: 0x3701
          DacReg[103]: 0xf30e
          DacReg[104]: 0xf90b
          DacReg[105]: 0x4a0b
          DacReg[106]: 0x170f
          DacReg[107]: 0xee0c
          DacReg[108]: 0x0007
          DacReg[109]: 0x00ff
          DacReg[110]: 0x0000
          DacReg[111]: 0x0000
          DacReg[112]: 0x0000
          DacReg[113]: 0x0000
          DacReg[114]: 0x0000
          DacReg[115]: 0x0000
          DacReg[116]: 0x0000
          DacReg[117]: 0x0000
          DacReg[118]: 0x0000
          DacReg[119]: 0x0000
          DacReg[120]: 0x0000
          DacReg[121]: 0x0000
          DacReg[122]: 0x0000
          DacReg[123]: 0x0000
          DacReg[124]: 0x0000
          DacReg[125]: 0x0000
          EnableTx: 0x1
        ADC[0]:
          SYNCB_POL: 0x1
          SLOW_SP_EN1: 0x1 # 0x1 = ADC sampling rates are slower than 2.5 GSPS
          SLOW_SP_EN2: 0x1 # 0x1 = ADC sampling rates are slower than 2.5 GSPS       
          JESD_OUTPUT_SWING: 0x4 # 0x4 = 960 mVPP (max. swing)
          CHA:
            ########################
            # DECIMATION FILTER PAGE
            ########################
            DDC_EN: 0x1
            DECIM_FACTOR: 0x0
            DUAL_BAND_EN: 0x0
            REAL_OUT_EN: 0x0
            DDC0_NCO1_LSB: 0x20
            DDC0_NCO1_MSB: 0x4E
            DDC0_NCO2_LSB: 0x00
            DDC0_NCO2_MSB: 0x00
            DDC0_NCO3_LSB: 0x00
            DDC0_NCO3_MSB: 0x00
            DDC0_NCO4_LSB: 0x00
            DDC0_NCO4_MSB: 0x00
            NCO_SEL_PIN: 0x00
            NCO_SEL: 0x00
            LMFC_RESET_MODE: 0x00
            DDC0_6DB_GAIN: 0x01
            DDC1_6DB_GAIN: 0x01
            DDC_DET_LAT: 0x51
            WBF_6DB_GAIN: 0x01          
            CUSTOM_PATTERN1_LSB: 0x00
            CUSTOM_PATTERN1_MSB: 0x00
            CUSTOM_PATTERN2_LSB: 0x00
            CUSTOM_PATTERN2_MSB: 0x00
            TEST_PATTERN_SEL: 0x00
            TEST_PAT_RES: 0x00
            TP_RES_EN: 0x00          
            ########################
            # JESD DIGITAL PAGE
            ########################         
            JESD_MODE0: 0x0
            12BIT MODE: 0x0
            SYNC_REG_EN: 0x0
            SYNC_REG: 0x0          
            RAMP_12BIT: 0x0
            JESD_MODE2: 0x1
            JESD_MODE1: 0x0
            LMFC_MASK_RESET: 0x0
            LINK_LAY_RPAT: 0x0
            LINK_LAYER_TESTMODE: 0x0
            40X_MODE: 0x7
            PLL_MODE: 0x2
            SEL_EMP_LANE0: 0x7
            SEL_EMP_LANE1: 0x7
            SEL_EMP_LANE2: 0x7
            SEL_EMP_LANE3: 0x7
            TX_LINK_DIS: 0x0
            FRAME_ALIGN: 0x0
            LANE_ALIGN: 0x0
            TESTMODE_EN: 0x0
            CTRL_K: 0x1
            FRAMES_PER_MULTIFRAME: 0x0F
          CHB:
            ########################
            # DECIMATION FILTER PAGE
            ########################
            DDC_EN: 0x1
            DECIM_FACTOR: 0x0
            DUAL_BAND_EN: 0x0
            REAL_OUT_EN: 0x0
            DDC0_NCO1_LSB: 0x20
            DDC0_NCO1_MSB: 0x4E
            DDC0_NCO2_LSB: 0x00
            DDC0_NCO2_MSB: 0x00
            DDC0_NCO3_LSB: 0x00
            DDC0_NCO3_MSB: 0x00
            DDC0_NCO4_LSB: 0x00
            DDC0_NCO4_MSB: 0x00
            NCO_SEL_PIN: 0x00
            NCO_SEL: 0x00
            LMFC_RESET_MODE: 0x00
            DDC0_6DB_GAIN: 0x01
            DDC1_6DB_GAIN: 0x01
            DDC_DET_LAT: 0x51
            WBF_6DB_GAIN: 0x01          
            CUSTOM_PATTERN1_LSB: 0x00
            CUSTOM_PATTERN1_MSB: 0x00
            CUSTOM_PATTERN2_LSB: 0x00
            CUSTOM_PATTERN2_MSB: 0x00
            TEST_PATTERN_SEL: 0x00
            TEST_PAT_RES: 0x00
            TP_RES_EN: 0x00          
            ########################
            # JESD DIGITAL PAGE
            ########################         
            JESD_MODE0: 0x0
            12BIT MODE: 0x0
            SYNC_REG_EN: 0x0
            SYNC_REG: 0x0          
            RAMP_12BIT: 0x0
            JESD_MODE2: 0x1
            JESD_MODE1: 0x0
            LMFC_MASK_RESET: 0x0
            LINK_LAY_RPAT: 0x0
            LINK_LAYER_TESTMODE: 0x0
            40X_MODE: 0x7
            PLL_MODE: 0x2
            SEL_EMP_LANE0: 0x7
            SEL_EMP_LANE1: 0x7
            SEL_EMP_LANE2: 0x7
            SEL_EMP_LANE3: 0x7
            TX_LINK_DIS: 0x0
            FRAME_ALIGN: 0x0
            LANE_ALIGN: 0x0
            TESTMODE_EN: 0x0
            CTRL_K: 0x1
            FRAMES_PER_MULTIFRAME: 0x0F     
        ADC[1]:
          SYNCB_POL: 0x1
          SLOW_SP_EN1: 0x1 # 0x1 = ADC sampling rates are slower than 2.5 GSPS
          SLOW_SP_EN2: 0x1 # 0x1 = ADC sampling rates are slower than 2.5 GSPS       
          JESD_OUTPUT_SWING: 0x4 # 0x4 = 960 mVPP (max. swing)
          CHA:
            ########################
            # DECIMATION FILTER PAGE
            ########################
            DDC_EN: 0x1
            DECIM_FACTOR: 0x0
            DUAL_BAND_EN: 0x0
            REAL_OUT_EN: 0x0
            DDC0_NCO1_LSB: 0x20
            DDC0_NCO1_MSB: 0x4E
            DDC0_NCO2_LSB: 0x00
            DDC0_NCO2_MSB: 0x00
            DDC0_NCO3_LSB: 0x00
            DDC0_NCO3_MSB: 0x00
            DDC0_NCO4_LSB: 0x00
            DDC0_NCO4_MSB: 0x00
            NCO_SEL_PIN: 0x00
            NCO_SEL: 0x00
            LMFC_RESET_MODE: 0x00
            DDC0_6DB_GAIN: 0x01
            DDC1_6DB_GAIN: 0x01
            DDC_DET_LAT: 0x51
            WBF_6DB_GAIN: 0x01          
            CUSTOM_PATTERN1_LSB: 0x00
            CUSTOM_PATTERN1_MSB: 0x00
            CUSTOM_PATTERN2_LSB: 0x00
            CUSTOM_PATTERN2_MSB: 0x00
            TEST_PATTERN_SEL: 0x00
            TEST_PAT_RES: 0x00
            TP_RES_EN: 0x00          
            ########################
            # JESD DIGITAL PAGE
            ########################         
            JESD_MODE0: 0x0
            12BIT MODE: 0x0
            SYNC_REG_EN: 0x0
            SYNC_REG: 0x0          
            RAMP_12BIT: 0x0
            JESD_MODE2: 0x1
            JESD_MODE1: 0x0
            LMFC_MASK_RESET: 0x0
            LINK_LAY_RPAT: 0x0
            LINK_LAYER_TESTMODE: 0x0
            40X_MODE: 0x7
            PLL_MODE: 0x2
            SEL_EMP_LANE0: 0x7
            SEL_EMP_LANE1: 0x7
            SEL_EMP_LANE2: 0x7
            SEL_EMP_LANE3: 0x7
            TX_LINK_DIS: 0x0
            FRAME_ALIGN: 0x0
            LANE_ALIGN: 0x0
            TESTMODE_EN: 0x0
            CTRL_K: 0x1
            FRAMES_PER_MULTIFRAME: 0x0F
          CHB:
            ########################
            # DECIMATION FILTER PAGE
            ########################
            DDC_EN: 0x1
            DECIM_FACTOR: 0x0
            DUAL_BAND_EN: 0x0
            REAL_OUT_EN: 0x0
            DDC0_NCO1_LSB: 0x20
            DDC0_NCO1_MSB: 0x4E
            DDC0_NCO2_LSB: 0x00
            DDC0_NCO2_MSB: 0x00
            DDC0_NCO3_LSB: 0x00
            DDC0_NCO3_MSB: 0x00
            DDC0_NCO4_LSB: 0x00
            DDC0_NCO4_MSB: 0x00
            NCO_SEL_PIN: 0x00
            NCO_SEL: 0x00
            LMFC_RESET_MODE: 0x00
            DDC0_6DB_GAIN: 0x01
            DDC1_6DB_GAIN: 0x01
            DDC_DET_LAT: 0x51
            WBF_6DB_GAIN: 0x01          
            CUSTOM_PATTERN1_LSB: 0x00
            CUSTOM_PATTERN1_MSB: 0x00
            CUSTOM_PATTERN2_LSB: 0x00
            CUSTOM_PATTERN2_MSB: 0x00
            TEST_PATTERN_SEL: 0x00
            TEST_PAT_RES: 0x00
            TP_RES_EN: 0x00          
            ########################
            # JESD DIGITAL PAGE
            ########################         
            JESD_MODE0: 0x0
            12BIT MODE: 0x0
            SYNC_REG_EN: 0x0
            SYNC_REG: 0x0          
            RAMP_12BIT: 0x0
            JESD_MODE2: 0x1
            JESD_MODE1: 0x0
            LMFC_MASK_RESET: 0x0
            LINK_LAY_RPAT: 0x0
            LINK_LAYER_TESTMODE: 0x0
            40X_MODE: 0x7
            PLL_MODE: 0x2
            SEL_EMP_LANE0: 0x7
            SEL_EMP_LANE1: 0x7
            SEL_EMP_LANE2: 0x7
            SEL_EMP_LANE3: 0x7
            TX_LINK_DIS: 0x0
            FRAME_ALIGN: 0x0
            LANE_ALIGN: 0x0
            TESTMODE_EN: 0x0
            CTRL_K: 0x1
            FRAMES_PER_MULTIFRAME: 0x0F    
    AppTopJesd[1]:
      JesdRx:
        Enable: 0x3FF
        # Enable: 0x73
        # Enable: 0x3F3
        # Enable: 0x80 # JESD7 is broken??
        # Enable: 0x100
        # Enable: 0x200 # JESD7 is broken
        InvertAdcData: 0x00
        LinkErrMask: 0x3f
        ScrambleEnable: Disabled
        ResetGTs: 0x0
        ClearErrors: 0x0
        InvertSync: Inverted
        ReplaceEnable: Enabled
        SubClass: 0x1
        SysrefDelay: 0x00
      JesdTx:
        Enable: 0x3FF
        # Enable: 0x0
        InvertDacData: 0x00
        HighAmplitudeVal: 0x0000ffff
        LowAmplitudeVal: 0x00000000
        SquarePeriod: 0x0001
        RampStep: 0x0001
        ScrambleEnable: Disabled
        TestSigEnable: 0x1
        InvertSync: 0x0
        ResetGTs: 0x0
        ReplaceEnable: 0x1
        ClearErrors: 0x0
        SubClass: 0x1      
        